module.exports = {
	en_GB: {
		INTRODUCTION : "Hi, I'm NIMA. I'm your smart friend. I can find NHS facilities near you. And this is only the beginning.",
	    INPUT_GREET1 : 'hi',
	    INPUT_GREET2 : 'hello',
	    INPUT_GREET3 : 'hey',
	    RESET : 'Lets do a fresh start...',
	    INPUT_RESET : 'reset',
	    GREETING: 'Hi, ',
	    GREETING_POST: ' nice to see you here :)',
	    LOCATION: 'Ready to go! Now send me your location or write me your postcode to help you out.',
	    THANKS: "Thank you (Y)",
	    SEARCH_OPTIONS: "Thank you (Y). Now I can find for you the nearest...",
	    SEARCH_OPTIONS_REPEAT: "Of course :D! Let me find for you the nearest...",
	    ERROR: 'That is so funny! :D',
	    INVALID_POSTCODE: "Mmm... It doesn't look like a valid postcode, do you want to give another try?",
	    LANG_SET: "I've set your language to",
	    LANG_CHANGE: ', would you like to change it?',
		WEBSITE : "View Website",
		MAP: "Find us",
		SEARCH_AGAIN: "Search Again",
		NOPHONE: "No phone info"
	},
	fr_FR: {
		INTRODUCTION : "Salut, je m'appelle NIMA. Je suis votre ami habile. Je peux trouver les aménagement de NHS près de vous. Ce n'est que le début",
		INPUT_GREET1 : 'salut',
		INPUT_GREET2 : 'bonjour',
		INPUT_GREET3 : 'tiens',
		RESET: "Recommençons...",
		INPUT_RESET : 'reset',
		GREETING: "Salut, ",
		GREETING_POST: "Ravi de vous voir :)",
		LOCATION: "Bien, m'envoye votre adresse ou votre code postal pour obtenir des informations sur votre zone",
		THANKS: "Merci",
		SEARCH_OPTIONS: "Merci beaucoup. Maintenant je peux trouver le plus proche...",
		SEARCH_OPTIONS_REPEAT: "Bien sûr :D! Laissez moi trouver le plus proche...",
		ERROR: "Desolée, pouvez-vous cela d'une manière différente?",
		INVALID_POSTCODE: "Il semble que c'est une code postal invalide, voulez-vous essayer à nouveau?",
	    LANG_SET: "J'ai règlé votre langue à",
	    LANG_CHANGE: ', voulez-vous le modifier?',
		WEBSITE : "View Website",
		MAP: "Find us",
		SEARCH_AGAIN: "Search Again",
		NOPHONE: "No phone info"
	},
	es_LA: {
		INTRODUCTION : "Hola, me llamo NIMA. Soy tu amigo inteligente. Te puedo ayudar a encontrar entidades de NHS. Y esto es solo el principio.",
		INPUT_GREET1 : 'hola',
		INPUT_GREET2 : 'hey',
		INPUT_GREET3 : 'hola',
		RESET : 'Ok, empecemos de nuevo :)',
		INPUT_RESET : 'reset',
		GREETING: 'Hola, ',
		GREETING_POST: ' bienvenido!',
		LOCATION: 'Todo listo! Ahora enviame tu localizacion o escribe tu codigo postal para que pueda ayudarte',
		THANKS: "Muchas gracias (Y)",
		SEARCH_OPTIONS: "Muchas gracias (Y). Ahora puedo encontrar cerca de ti...",
		SEARCH_OPTIONS_REPEAT: "Por supuesto :D! Que necesitas encontrar cerca de ti:",
		ERROR: 'Jajaja eso ha sido muy gracioso :D',
		INVALID_POSTCODE: "Mmm... No parece un codigo postal correcto...Lo intentamos de nuevo?",
		LANG_SET: "Ok, hablemos en",
		LANG_CHANGE: ', te gustaria cambiarlo?',
		WEBSITE : "Ver Web",
		MAP: "Find us",
		SEARCH_AGAIN: "Cambiar la busqueda",
		NOPHONE: "Sin info de contacto"
	}
}